-- Disable foreign key checks temporarily (PostgreSQL equivalent)
SET session_replication_role = replica;

DROP TABLE IF EXISTS TransactionLines CASCADE;
DROP TABLE IF EXISTS Transactions CASCADE;
DROP TABLE IF EXISTS Accounts CASCADE;

-- Re-enable foreign key checks
SET session_replication_role = DEFAULT;

-- Create tables with SERIAL for auto-increment (PostgreSQL equivalent to AUTOINCREMENT)
CREATE TABLE IF NOT EXISTS Accounts (
    Id SERIAL PRIMARY KEY,
    Name TEXT NOT NULL CHECK(LENGTH(Name) <= 200),
    Description TEXT NOT NULL,
    FinancialStatement TEXT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ParentId INTEGER,
    IsSystem BOOLEAN NOT NULL DEFAULT FALSE,  -- FALSE=User visible, TRUE=System/Hidden
    FOREIGN KEY (ParentId) REFERENCES Accounts(Id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Transactions (
    Id SERIAL PRIMARY KEY,
    Description TEXT,
    Date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TransactionLines (
    Id SERIAL PRIMARY KEY,
    TransactionId INTEGER NOT NULL,
    AccountId INTEGER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Description TEXT,
    Quantity INTEGER NOT NULL DEFAULT 1 CHECK (Quantity >= 1),
    FOREIGN KEY (TransactionId) REFERENCES Transactions(Id) ON DELETE CASCADE,
    FOREIGN KEY (AccountId) REFERENCES Accounts(Id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS IX_Accounts_ParentId ON Accounts(ParentId);
CREATE INDEX IF NOT EXISTS IX_TransactionLines_TransactionId ON TransactionLines(TransactionId);
CREATE INDEX IF NOT EXISTS IX_TransactionLines_AccountId ON TransactionLines(AccountId);

--------------------------------------------------------------------------------
-- Seed top-level accounts (Id autogenerated via SERIAL)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Auto & Transport',        'Vehicle and transportation costs',         'EXPENSE', NULL, FALSE),
('Travel & Life Style',     'Travel, leisure and lifestyle expenses',  'EXPENSE', NULL, FALSE),
('Shopping',                'Clothing, furniture, electronics, etc.',  'EXPENSE', NULL, FALSE),
('Food & Dining',           'Restaurants, groceries, coffee',          'EXPENSE', NULL, FALSE),
('Utilities',               'Electricity, gas, phone, water, etc.',    'EXPENSE', NULL, FALSE),
('Housing',                 'Rent, mortgage, home maintenance',        'EXPENSE', NULL, FALSE),
('Income',                  'All income sources',                      'REVENUE', NULL, FALSE),
('Savings',                 'Bank savings and reserve accounts',       'ASSET', NULL, FALSE),
('Cash & Bank',             'Cash, checking and bank accounts',        'ASSET', NULL, TRUE),  -- System account
('Liabilities',             'Credit cards, loans and other liabilities','LIABILITY', NULL, FALSE),
('Equity',                  'Owner equity / net worth buckets',        'EQUITY', NULL, TRUE),  -- System account
('Personal Care',           'Health, hygiene, and personal grooming',   'EXPENSE', NULL, FALSE),
('Health & Medicine',        'Healthcare, medications, and wellness',   'EXPENSE', NULL, FALSE),
('Alcohol & Tobacco',        'Alcoholic beverages and tobacco products', 'EXPENSE', NULL, FALSE),
('Tools & Equipment',        'Tools for home repairs and maintenance',   'EXPENSE', NULL, FALSE),
('Cleaning Supplies',        'Household cleaning products',               'EXPENSE', NULL, FALSE),
('Office & Stationery',      'Home office and writing supplies',         'EXPENSE', NULL, FALSE),
('Gifts & Donations',        'Gift purchases and charitable contributions', 'EXPENSE', NULL, FALSE),
('Other Expenses',          'Miscellaneous expense buckets',           'EXPENSE', NULL, FALSE);

--------------------------------------------------------------------------------
-- Auto & Transport subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Maintenance',        'Car maintenance and repairs',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1), FALSE),
('Gas',                'Fuel purchases',                        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1), FALSE),
('Taxi & Ride Shares', 'Uber, Lyft, taxis',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1), FALSE),
('Public Transit',     'Subway, buses, transit tickets',        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1), FALSE),
('Parking & Tolls',    'Parking fees and tolls',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Travel & Life Style subaccounts (includes travel-specific martial arts/gym)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Travel & Vacations',       'Trips, flights, hotels',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1), FALSE),
('Pets',                     'Pet food, vet, supplies',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1), FALSE),
('Entertainment & Recreation','Movies, events, hobbies',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1), FALSE),
('Martial Arts (Travel)',    'Martial arts classes/training while on vacation', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1), FALSE),
('Gym (Travel)',             'Gym passes or classes while on vacation', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1), FALSE),
('Restaurants (Travel)',     'Dining while traveling',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Shopping subaccounts (including electronics/appliances)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Clothing',                 'Clothes and accessories',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1), FALSE),
('Furniture & Housewares',   'Furniture, home goods',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1), FALSE),
('Other Shopping',           'General shopping misc',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1), FALSE),
('Electronics & Appliances','Fridges, microwaves, TVs, computers',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Food & Dining subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Restaurants',              'Eating out',                             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1), FALSE),
('Groceries',                'Supermarket and grocery stores',         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1), FALSE),
('Coffee Shops',             'Cafes and coffee purchases',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Utilities subaccounts (electricity, gas, phone, etc.)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Electricity',              'Electric bills',                         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1), FALSE),
('Gas (Utility)',            'Home heating / gas utility',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1), FALSE),
('Water',                    'Water bills',                            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1), FALSE),
('Phone & Internet',         'Mobile phone and internet services',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1), FALSE),
('Trash & Recycling',        'Waste collection fees',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Housing subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Rent',                     'Monthly rent payments',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1), FALSE),
('Mortgage',                 'Mortgage payments (interest/principal)', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1), FALSE),
('Home Insurance',           'Home insurance premiums',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1), FALSE),
('Property Taxes',           'Local property taxes',                   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1), FALSE),
('Home Maintenance',         'Repairs and upkeep',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Income subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Salary',                   'Employment wages and salary',            'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1), FALSE),
('Business Income',          'Freelance or business revenue',          'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1), FALSE),
('Investment Income',        'Dividends, capital gains',               'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1), FALSE),
('Interest Income',          'Bank interest',                          'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1), FALSE),
('Refunds & Rebates',        'Refunds, rebates, returned purchases',   'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Savings subaccounts (User visible - savings goals)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Emergency Fund',           'Short-term emergency savings'                      , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1), FALSE),
('Business Fund',            'Fund to create or invest on a business'            , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1), FALSE),
('Motorcycle Fund',          'Fund to buy a new one or to spent in a current one', 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1), FALSE),
('Retirement',               'Retirement accounts (IRA, 401k)'                   , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1), FALSE),
('Short Term Savings',       'Planned short-term goals'                          , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1), FALSE),
('Long Term Savings',        'Long-term goals and investments'                   , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Cash & Bank subaccounts (SYSTEM ACCOUNTS - hidden from users)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Cash on Hand',             'Physical cash (system use)',              'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1), TRUE),
('Checking Account',         'Primary checking account (system use)',   'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1), TRUE),
('Bank Savings Account',     'Bank savings account (system use)',       'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1), TRUE);

--------------------------------------------------------------------------------
-- Liabilities subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Credit Card',              'Credit card balances',                   'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1), FALSE),
('Auto Loan',                'Auto loan principal',                    'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1), FALSE),
('Student Loan',             'Student loan balances',                  'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1), FALSE),
('Mortgage Loan',            'Mortgage principal',                     'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1), FALSE),
('Other Liabilities',        'Other owed balances',                    'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Other Expenses subaccounts (includes local martial arts/gym variants)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Subscriptions',            'Streaming, software, memberships',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1), FALSE),
('Fees & Charges',           'Service fees, late fees',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1), FALSE),
('Bank Fees',                'Account and transaction fees',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1), FALSE),
('Miscellaneous',            'Unclassified small expenses',            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1), FALSE),
('Martial Arts (Local)',     'Martial arts classes and training (local)', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1), FALSE),
('Gym (Local)',              'Gym memberships or classes (local)',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Electronics & Appliances detailed items under Shopping
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Fridge',                   'Refrigerator purchase',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1), FALSE),
('Microwave',                'Microwave purchase',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1), FALSE),
('TV',                       'Television purchase',                    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1), FALSE),
('Computer',                 'Laptop / desktop purchase',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1), FALSE),
('Other Electronics',        'Other electronic devices',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Equity subaccounts (SYSTEM ACCOUNTS - all hidden from users)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Owner''s Capital',         'Initial and additional owner investments (system)',     'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1), TRUE),
('Retained Earnings',        'Accumulated profits not distributed (system)',           'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1), TRUE),
('Current Year Earnings',    'Net income for the current fiscal year (system)',        'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1), TRUE),
('Dividends/Drawings',       'Owner withdrawals or dividends paid (system)',           'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1), TRUE),
('Paid-in Capital',          'Additional paid-in capital beyond par value (system)',   'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1), TRUE),
('Treasury Stock',           'Company''s own shares repurchased (system)',             'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1), TRUE),
('Other Comprehensive Income', 'Unrealized gains/losses not in net income (system)',   'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1), TRUE);

--------------------------------------------------------------------------------
-- Personal Care & Hygiene (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Shampoo & Conditioner',    'Hair care products',                          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE),
('Soap & Body Wash',         'Bathing and cleansing products',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE),
('Deodorant',                'Antiperspirants and deodorants',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE),
('Toothpaste & Oral Care',   'Dental hygiene products',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE),
('Shaving & Grooming',       'Razors, shaving cream, trimmers',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE),
('Skincare',                 'Moisturizers, sunscreen, facial products',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE),
('Makeup & Cosmetics',       'Cosmetic products',                           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE),
('Haircuts & Salon',         'Professional haircuts and salon services',    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Health & Medicine (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Prescriptions',            'Prescription medications',                    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('Over-the-Counter Drugs',   'OTC medicines (pain relievers, cold meds)',   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('Vitamins & Supplements',   'Dietary supplements and vitamins',            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('Doctor Visits',            'Medical consultations and checkups',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('Dental Care',              'Dentist visits, cleanings, procedures',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('Vision Care',              'Eye exams, glasses, contact lenses',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('Health Insurance',         'Health insurance premiums',                   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('Therapy & Mental Health',  'Counseling, therapy sessions',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE),
('First Aid Supplies',       'Bandages, antiseptics, first aid kits',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Alcohol & Tobacco (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Beer',                     'Beer purchases',                              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1), FALSE),
('Wine',                     'Wine purchases',                              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1), FALSE),
('Spirits & Liquor',         'Hard liquor and spirits',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1), FALSE),
('Cigarettes',               'Cigarette purchases',                         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1), FALSE),
('Vaping Products',          'E-cigarettes, vape juice, accessories',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1), FALSE),
('Cigars',                   'Cigar purchases',                             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Home Maintenance & Tools (expanding under Housing or as new top-level)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Hand Tools',               'Wrenches, screwdrivers, hammers',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1), FALSE),
('Power Tools',              'Drills, saws, sanders',                        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1), FALSE),
('Mechanic Tools',           'Car repair tools, jacks, stands',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1), FALSE),
('Gardening Tools',          'Shovels, rakes, trimmers',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1), FALSE),
('Tool Storage',             'Toolboxes, pegboards, organizers',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1), FALSE),
('Safety Equipment',         'Gloves, goggles, masks, safety gear',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Cleaning Supplies (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('All-Purpose Cleaner',      'Multi-surface cleaning solutions',            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1), FALSE),
('Laundry Detergent',        'Laundry soap, fabric softener, stain removers', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1), FALSE),
('Dish Soap',                'Dishwashing liquid and dishwasher detergent',  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1), FALSE),
('Bathroom Cleaners',        'Toilet, tub, and tile cleaners',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1), FALSE),
('Floor Cleaners',           'Mop solutions, floor wax',                    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1), FALSE),
('Paper Products',           'Paper towels, tissues, toilet paper',         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1), FALSE),
('Trash Bags',               'Garbage bags and liners',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Office & Stationery (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Paper & Envelopes',        'Printer paper, envelopes, notepads',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1), FALSE),
('Pens & Pencils',           'Writing instruments and refills',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1), FALSE),
('Printer Ink & Toner',      'Printer cartridges',                          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1), FALSE),
('Office Furniture',         'Desks, chairs, filing cabinets',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1), FALSE),
('Postage & Shipping',       'Stamps, shipping supplies',                   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1), FALSE),
('Calendars & Planners',     'Organizational tools',                        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1), FALSE);

--------------------------------------------------------------------------------
-- Gifts & Donations (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId, IsSystem) VALUES
('Birthday Gifts',           'Birthday presents for others',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1), FALSE),
('Holiday Gifts',            'Christmas, holiday gift giving',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1), FALSE),
('Charitable Donations',     'Donations to charities and causes',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1), FALSE),
('Wedding Gifts',            'Wedding presents',                            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1), FALSE),
('Baby Gifts',               'Baby shower and new baby gifts',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1), FALSE),
('Gift Wrapping',            'Wrapping paper, bags, ribbons',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1), FALSE);